import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | QuizKraft",
  description: "QuizKraft terms of service for the AI worksheet and quiz generator. Free plan, Pro subscription, cancellation, and AI content policy.",
  alternates: { canonical: "https://www.quizkraft.tech/terms" },
};

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1 bg-canvas">
      <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-14 w-full">
        <h1
          className="text-4xl font-medium text-ink tracking-[-0.02em] mb-10"
          style={{ fontFamily: "var(--font-fraunces), Georgia, serif" }}
        >
          Terms of Service
        </h1>

        <div className="space-y-8 text-sm text-muted leading-relaxed">
          {[
            {
              title: "1. Use of the service",
              body: "QuizKraft provides an AI-powered worksheet and quiz generation service. By using QuizKraft, you agree to use it only for lawful purposes and in accordance with these terms.",
            },
            {
              title: "2. Free and paid plans",
              body: "The free plan allows 1 worksheet generation per month. Pro and School plans are billed monthly and may be cancelled at any time. Cancellation takes effect at the end of the current billing period.",
            },
            {
              title: "3. AI-generated content",
              body: "Content generated by QuizKraft is produced by AI and may contain errors. You are responsible for reviewing all generated content before distributing it to students or others. QuizKraft makes no warranty as to the accuracy or fitness for purpose of generated content.",
            },
            {
              title: "4. Intellectual property",
              body: "You retain ownership of any content you upload (source material, notes, PDFs). AI-generated worksheets produced using QuizKraft may be used freely for personal and classroom purposes.",
            },
            {
              title: "5. Limitations of liability",
              body: "QuizKraft is provided as-is. We are not liable for any indirect, incidental, or consequential damages arising from the use or inability to use the service.",
            },
            {
              title: "6. Changes to terms",
              body: "We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the revised terms.",
            },
            {
              title: "7. Contact",
              body: "Questions about these terms? Email us at hello@quizkraft.app.",
            },
          ].map((s) => (
            <div key={s.title}>
              <h2 className="font-semibold text-ink mb-2">{s.title}</h2>
              <p>{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
